<a href="https://colab.research.google.com/github/sushilsahoo06/Pytorch/blob/main/00_pytorch_fundametal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


list vs numpy

In [3]:
from time import process_time

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time - start_time)

0.0005905130000005698


In [7]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time - start_time)

0.00013295299999960264


Numpy Array


In [8]:
list=[1,2,3,4,5]
print(list)
type(list)


[1, 2, 3, 4, 5]


list

In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

creating a 1D array

In [10]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
a.shape

(5,)

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])##array of rows-2 & col-4
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
# create a numpy array of zeros
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a perticular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an ientity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values
b=np.random.random((4,5))
print(b)

[[0.52582768 0.09298407 0.13045673 0.11318734 0.37626651]
 [0.49485619 0.71856333 0.44837773 0.73383834 0.09599275]
 [0.78220618 0.69214678 0.99098291 0.30693025 0.44137235]
 [0.42880138 0.20846721 0.15943587 0.58316084 0.79767009]]


In [18]:
# random integer value array with a spesific range
c=np.random.randint(10,100,(3,5))
print(c)

[[90 97 42 24 17]
 [13 37 24 24 65]
 [84 71 73 15 36]]


In [20]:
# array of eveny spaced values -->specifying the number of values required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of eveny spaced values -->specifying steps
e=np.arange(10,30,5)
print(e)


[10 15 20 25]


In [22]:
#covert a list to a numpy array
list_2=[10,20,30,40,50]
np_array=np.asarray(list_2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy arraay

In [26]:
a=np.random.randint(10,100,(3,4))
print(a)
print(a.shape)
print(a.ndim)#number of dimensions
print(a.size)

[[63 60 14 53]
 [90 88 96 39]
 [21 32 54 72]]
(3, 4)
2
12


Mathemetical operactions on a np array

In [27]:
list_1=[1,2,3,4,5]
lists_2=[6,7,8,9]
print(list_1+lists_2)#concatinate or joins two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
a=np.random.randint(10,30,(4,4))
b=np.random.randint(20,40,(4,4))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[29 16 22 16]
 [24 19 28 14]
 [20 22 25 17]
 [23 14 26 13]]
[[36 34 24 29]
 [33 20 28 34]
 [36 32 20 35]
 [34 33 28 35]]
[[65 50 46 45]
 [57 39 56 48]
 [56 54 45 52]
 [57 47 54 48]]
[[ -7 -18  -2 -13]
 [ -9  -1   0 -20]
 [-16 -10   5 -18]
 [-11 -19  -2 -22]]
[[1044  544  528  464]
 [ 792  380  784  476]
 [ 720  704  500  595]
 [ 782  462  728  455]]
[[0.80555556 0.47058824 0.91666667 0.55172414]
 [0.72727273 0.95       1.         0.41176471]
 [0.55555556 0.6875     1.25       0.48571429]
 [0.67647059 0.42424242 0.92857143 0.37142857]]


[[29 16 22 16]
 [24 19 28 14]
 [20 22 25 17]
 [23 14 26 13]]
[[36 34 24 29]
 [33 20 28 34]
 [36 32 20 35]
 [34 33 28 35]]


In [30]:
a=np.random.randint(10,30,(4,4))#using numpy
b=np.random.randint(20,40,(4,4))
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 16 19 13]
 [10 12 23 25]
 [12 29 15 25]
 [23 16 22 13]]
[[22 33 33 35]
 [23 20 24 29]
 [21 20 25 29]
 [37 24 33 35]]
[[47 49 52 48]
 [33 32 47 54]
 [33 49 40 54]
 [60 40 55 48]]
[[  3 -17 -14 -22]
 [-13  -8  -1  -4]
 [ -9   9 -10  -4]
 [-14  -8 -11 -22]]
[[550 528 627 455]
 [230 240 552 725]
 [252 580 375 725]
 [851 384 726 455]]
[[1.13636364 0.48484848 0.57575758 0.37142857]
 [0.43478261 0.6        0.95833333 0.86206897]
 [0.57142857 1.45       0.6        0.86206897]
 [0.62162162 0.66666667 0.66666667 0.37142857]]


In [31]:
#tanspose the matrix
trans=np.transpose(a)
print(trans)

[[25 10 12 23]
 [16 12 29 16]
 [19 23 15 22]
 [13 25 25 13]]


In [43]:
#reshaping array-->not working
a=np.random.randint(10,20,(3,3))
print(a)
print(a.shape)
c=a.reshape(1,9)
print(c)
print(c.shape)


[[14 18 19]
 [16 16 14]
 [11 19 12]]
(3, 3)
[[14 18 19 16 16 14 11 19 12]]
(1, 9)
