<a href="https://colab.research.google.com/github/sushilsahoo06/Pytorch/blob/main/00_pytorch_fundametal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


list vs numpy

In [3]:
from time import process_time

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time - start_time)

0.0005905130000005698


In [7]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time - start_time)

0.00013295299999960264


Numpy Array


In [8]:
list=[1,2,3,4,5]
print(list)
type(list)


[1, 2, 3, 4, 5]


list

In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

creating a 1D array

In [10]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
a.shape

(5,)

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])##array of rows-2 & col-4
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
# create a numpy array of zeros
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#create a numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a perticular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an ientity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
