<a href="https://colab.research.google.com/github/sushilsahoo06/Pytorch/blob/main/RNN_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

how to convor text inputs to vectors

In [ ]:
import numpy as np
docs=['go india',
      'Hurry india',
      'hip hip hurry',
      'jitega bhai jitega RCB jitega',
      'iss sala CUP namde',
      'modi ji kii jai']


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
Tokenizer=Tokenizer(oov_token='sushil')
Tokenizer.fit_on_texts(docs)

In [ ]:
Tokenizer.word_index

{'sushil': 1,
 'jitega': 2,
 'india': 3,
 'hurry': 4,
 'hip': 5,
 'go': 6,
 'bhai': 7,
 'rcb': 8,
 'iss': 9,
 'sala': 10,
 'cup': 11,
 'namde': 12,
 'modi': 13,
 'ji': 14,
 'kii': 15,
 'jai': 16}

In [ ]:
Tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 2),
             ('hurry', 2),
             ('hip', 2),
             ('jitega', 3),
             ('bhai', 1),
             ('rcb', 1),
             ('iss', 1),
             ('sala', 1),
             ('cup', 1),
             ('namde', 1),
             ('modi', 1),
             ('ji', 1),
             ('kii', 1),
             ('jai', 1)])

In [ ]:
sequence=Tokenizer.texts_to_sequences(docs)
sequence

[[6, 3], [4, 3], [5, 5, 4], [2, 7, 2, 8, 2], [9, 10, 11, 12], [13, 14, 15, 16]]

In [ ]:
from keras.utils import pad_sequences#add padding


In [ ]:
sequence=pad_sequences(sequence,padding='post')
sequence

array([[ 6,  3,  0,  0,  0],
       [ 4,  3,  0,  0,  0],
       [ 5,  5,  4,  0,  0],
       [ 2,  7,  2,  8,  2],
       [ 9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0]], dtype=int32)

Embedding layers


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from IPython import get_ipython
from IPython.display import display

In [ ]:
model=Sequential()
model.add(Embedding(20,output_dim=2,input_length=7))#length output dimensions
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam',"ally")
pred=model.predict(sequence)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step
[[[-0.02128044 -0.01991071]
  [ 0.01136122  0.00529897]
  [-0.04242543 -0.01365734]
  [-0.04242543 -0.01365734]
  [-0.04242543 -0.01365734]]

 [[-0.01930387  0.02175919]
  [ 0.01136122  0.00529897]
  [-0.04242543 -0.01365734]
  [-0.04242543 -0.01365734]
  [-0.04242543 -0.01365734]]

 [[-0.03094598  0.03930006]
  [-0.03094598  0.03930006]
  [-0.01930387  0.02175919]
  [-0.04242543 -0.01365734]
  [-0.04242543 -0.01365734]]

 [[ 0.0029981   0.04219617]
  [ 0.01424337 -0.0256979 ]
  [ 0.0029981   0.04219617]
  [ 0.00381612  0.01634843]
  [ 0.0029981   0.04219617]]

 [[ 0.00383254 -0.03736182]
  [ 0.0365358   0.04573499]
  [ 0.02741169  0.00380832]
  [-0.03330152 -0.04975579]
  [-0.04242543 -0.01365734]]

 [[ 0.02804441 -0.03600876]
  [-0.01959994 -0.0197289 ]
  [-0.03226791  0.04017108]
  [ 0.01460813 -0.01008314]
  [-0.04242543 -0.01365734]]]
